#!/usr/bin/env bash

#遇错即停。任何一行报错，脚本立即停止，不再盲目执行后续命令
set -e
BLOG_DIR="/home/coper/blog_butterfly/"
cd "$BLOG_DIR"

hexo clean
python3 tools/generate_category_stats.py
git add .
git commit -m "Update blog content: $(date +'%Y-%m-%d %H:%M:%S')" || true
git push
hexo g -d

echo "---------------------------------------"
echo "🎉 Blog deployed successfully!"
echo "---------------------------------------"
